name: vision_agent
channels:
    - conda-forge
    - nvidia
    - defaults
dependencies:
    - cuda-nvcc
    - gin-config >=0.5.0
    - gymnasium >=0.28.1
    - jupyter
    - ninja
    - pip
    - python >=3.8,<3.12
    - tqdm
    - meshcat-shapes >=0.3.0
    - pink >=3.0.0,<4
    - pinocchio >=3.1.0,<4
    - qpmpc >=3.0.1,<4
    - qpsolvers >=4.2.0,<5
    - upkie >=6,<7
    - pip :
        - torch
        - torchvision
        - torchaudio
        - mediapy
        - moviepy
        - open3d
        - opencv-python
        - plyfile
        - scikit-image
        - trimesh
        - sb3-contrib
        - tensorboard
        - stable-baselines3[extra]
    - pip : 
        - third_party/2d-gaussian-splatting/submodules/diff-surfel-rasterization
        - third_party/2d-gaussian-splatting/submodules/simple-knn
        - third_party/pink_balancer